# Generated by Django 3.0.7 on 2022-12-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=25)),
                ('GPA', models.DecimalField(decimal_places=3, default='', max_digits=4)),
                ('age', models.PositiveIntegerField(default='')),
                ('address', models.CharField(default='', max_length=250)),
                ('Date', models.CharField(default='', max_length=15)),
                ('level', models.PositiveSmallIntegerField(default='0')),
                ('Gender', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile_number', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
