# Generated by Django 3.0.7 on 2022-12-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
