# Generated by Django 4.1.4 on 2023-01-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230102_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6),
        ),
    ]
