# Generated by Django 4.1.4 on 2023-01-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
    ]
