# Generated by Django 4.1.4 on 2023-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.CharField(default='Inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(max_length=50),
        ),
    ]
